name: Test, Parse PDFs, Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Parse PDFs into JSON
        run: npm run parse:pdfs

      - name: Commit generated data (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): update parsed syllabus JSON [skip ci]"
            git push
          fi

      - name: Run tests
        run: npm run test:ci

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build static site
        env:
          NEXT_PUBLIC_BASE_PATH: /agile-tester-exam-prep
        run: npm run build:static

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4